# Start indexing windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Set right status
#set -g status-right "#H %I:%M%P"

# Set status colours
set-option -g status-fg colour7
set-option -g status-bg colour236

# Set border colours
set-option -g pane-border-fg colour236
set-option -g pane-active-border-fg colour7

# Set window status colours
set-window-option -g window-status-current-fg colour2
set-window-option -g window-status-fg colour7
