# Use Ctrl-a for prefix
#unbind C-b
#set -g prefix F9
#bind F9 send-prefix

# Make sure $TERM is set properly
set -g default-terminal "xterm-256color"

# Start indexing windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically
set-option -g renumber-windows on

# Set window status
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"

# disable automatic renaming
set-option -g allow-rename off

# Set status colours
#set-option -g status-fg colour251
#set-option -g status-bg #282a2e

# Set border colours
#set-option -g pane-border-fg #282a2e
#set-option -g pane-active-border-fg colour251

# Set window status colours
#set-window-option -g window-status-current-fg colour2
#set-window-option -g window-status-fg colour251

# Set window activity colours
setw -g monitor-activity on
set-window-option -g window-status-activity-attr none
set-window-option -g window-status-activity-fg red

set -g status-left-length 32
set -g status-right-length 150
set -g status-fg "#c5c8c6"
set -g status-bg "#282a2e"
set -g window-status-activity-attr bold
set -g pane-border-fg colour245
set -g pane-active-border-fg colour4
set -g message-fg "#c5c8c6"
set -g message-bg "#282a2e"
set -g message-attr bold

set -g status-left '#[fg=#282a2e,bg=#c5c8c6,bold] #S #[fg=#c5c8c6,bg=#373b41,nobold] #[fg=#c5c8c6,bg=#373b41,bold] #H #[fg=colour238,bg=#282a2e,nobold] '
set -g window-status-format "#[fg=#c5c8c6,bg=#282a2e] #I #W "
set -g window-status-current-format "#[fg=#282a2e,bg=colour4] #[fg=#282a2e,bg=colour4,noreverse,bold] #I  #W #[fg=colour4,bg=#282a2e,nobold] "
set -g status-right "#[fg=color39,bg=#373b41] %Y-%m-%d %H:%M"
